name: Build static site and deploy to gh-pages branch

on:
  push:
    branches:
      - main

jobs:
  gh-pages:
    runs-on: self-hosted
    steps:
      - name: checkout
        uses: actions/checkout@v3
      
      - name: setup node
        uses: actions/setup-node@v3
        with:
          node-version: 16.15.x
          cache: npm

      - name: npm clean install
        run: npm ci

      - name: build
        run: node index.js

      - name: deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.ACTIONS_DEPLOY_KEY }}
          publish_dir: ./dist
